### ISSUE TITLE
Use of reserved variable name "request" forbidden in APM processor script

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#10]
https://github.com/checkout/link_checkoutcom/blob/3a476407ee146c5b639bc0ddb0d362bdaa6eb37f/int_checkoutcom/cartridge/scripts/payment/processor/CHECKOUTCOM_CREDIT_APM.js#L332

"request" is a reserved name in the SFCC system and is used as a global variable in the system. It should not be used to name custom variables as it will override the global variable and make it unaccessible. Please rename.

**Comment by michael-ugborikoko-cko** [comment]
Done
