### ISSUE TITLE
APM response checks

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#101]
https://github.com/checkout/link_checkoutcom/blob/248abe8a3550d2870cfb7fbda2e3c4b5da645a6e/Cartridges/int_checkoutcom/cartridge/scripts/helpers/ckoHelper.js#L323

Ideal seems to have the same response type as Sofort. Please check and confirm without closing the issue.

**Comment by michael-ugborikoko-cko** [comment]
ideal redirect confirmation object has own property action as shown bellow.
{
  "id":"pay_veo2uqkd5a6ejaf5dtgjx5urpa",
  "requested_on":"2020-02-07T01:00:17Z",
  "source":{
    "type":"ideal",
    "description":"00027997",
    "bic":"INGBNL2A",
    "iban":"NL53INGB0654422370",
    "account_holder":"Hr E G H Küppers en/of MW M.J. Küppers-Veeneman"
  },
  "amount":5618,
  "currency":"EUR",
  "payment_type":"Regular",
  "reference":"00027997",
  "status":"Captured",
  "approved":true,
  "risk":{
    "flagged":false
  },
  "customer":{
    "id":"cus_73dkhdxveuyutknjg37kpyfsh4",
    "email":"david.fiaty@checkout.com"
  },
  "payment_ip":"80.4.168.253",
  "metadata":{
    "integration_data":"SFCC Checkout.com Cartridge 19.1.0",
    "platform_data":"SiteGenesis Version: 19.10 Last Updated: Oct 21, 2019 (Compatibility Mode: 16.2)",
    "udf1":"ideal",
    "payment_processor":"CHECKOUTCOM_APM"
  },
  "actions":[
    {
      "id":"act_twhz7e243vnebbv7725ml5vfye",
      "type":"Capture",
      "response_code":"10000",
      "response_summary":"Approved"
    }
  ],
  "_links":{
    "self":{
      "href":"https://api.sandbox.checkout.com/payments/pay_veo2uqkd5a6ejaf5dtgjx5urpa"
    },
    "actions":{
      "href":"https://api.sandbox.checkout.com/payments/pay_veo2uqkd5a6ejaf5dtgjx5urpa/actions"
    },
    "refund":{
      "href":"https://api.sandbox.checkout.com/payments/pay_veo2uqkd5a6ejaf5dtgjx5urpa/refunds"
    }
  }
}
