### ISSUE TITLE
Code improvement needed

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#104]
https://github.com/checkout/link_checkoutcom/blob/248abe8a3550d2870cfb7fbda2e3c4b5da645a6e/Cartridges/int_checkoutcom/cartridge/scripts/helpers/ckoHelper.js#L302

This method's body could be written in 1 line:

function getFormattedNumber(num) {
    return num.replace(/\s/g, '');
}

Also, "number" is a reserved name in Javascript and should not be used to name variables.

**Comment by michael-ugborikoko-cko** [comment]
changed to return cardNumber.replace(/\s/g, "");

Done
