### ISSUE TITLE
Oxxo config setting missing

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#105]
https://github.com/checkout/link_checkoutcom/blob/248abe8a3550d2870cfb7fbda2e3c4b5da645a6e/metadata/meta/system-object-definitions.xml#L1

The "ckoOxxoEnabled" custom preference is missing for Oxxo. Please add it to the system-object-definitions.xml file.

**Comment by michael-ugborikoko-cko** [comment]
Done
