### ISSUE TITLE
Incorrect id for QPAY thumbnail

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#106]
https://github.com/checkout/link_checkoutcom/blob/248abe8a3550d2870cfb7fbda2e3c4b5da645a6e/Cartridges/int_checkoutcom/cartridge/templates/default/apm/qpay.isml#L4

The id of the QPAY image tag should be "qpay_thumb", not "knet_thumb"

**Comment by michael-ugborikoko-cko** [comment]
Changed.

Done
