### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#126]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L33

Unused commented code is not allowed in cartridges submitted to the market place. Please remove all commented/unused lines of code.

**Comment by michael-ugborikoko-cko** [comment]
Comment removed
