### ISSUE TITLE
Replace double quotes by single quotes

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#128]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L50

Prefer single quotes to doubles quotes where relevant for string declarations.

**Comment by michael-ugborikoko-cko** [comment]
formatted a adviced.
