### ISSUE TITLE
If/else and for statements formatting

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#129]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L45

https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L305

Related to this issue: https://github.com/checkout/link_checkoutcom/issues/127

If/else statements should be formatted properly with spaces:
if (test) { 

Instead of

if(test){

Same same with "for" statements

**Comment by michael-ugborikoko-cko** [comment]
Formatted as adviced
