### ISSUE TITLE
Remove white lines

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#130]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L46

Related to this issue: https://github.com/checkout/link_checkoutcom/issues/127

Too many unnecessary white lines in the file. Please remove all unneeded white lines according to coding standards.

**Comment by michael-ugborikoko-cko** [comment]
white lines remove
