### ISSUE TITLE
Security breach on csrf token

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#131]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L132

CSRF tokens are generated by the platforms and add a security layer to http requests.
They shouldn't be deleted before an AJAX request.

Instead, please refer to the documentation to implement a CSRF token validation in the AJAX request.

**Comment by michael-ugborikoko-cko** [comment]
code removed as it's not neccessary
