### ISSUE TITLE
Console.log statements handling

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#132]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L161

https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L250

There should be no console.log statements running in production ready code, unless debug mode is enabled. 

Please follow the logic below: 
1- Add a template hidden input field to retrieve the debug mode on/off value
2- Check the value of the debug mode field from the static file
3- Run console logging from the static file only if debug is on

**Comment by michael-ugborikoko-cko** [comment]
Removed as not needed
