### ISSUE TITLE
HTML in static files

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#133]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L199

Please avoid HTML in static js files where possible.
Instead, hard code empty/invisible HTML tags in HTML and call them by class or id in the js static file to add any relevant HTML tag content.

**Comment by michael-ugborikoko-cko** [comment]
Moved from static js file to html file
