### ISSUE TITLE
Code comment formatting

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#134]
https://github.com/checkout/link_checkoutcom/blob/9ae8b3f2e5fac2191fd869d617f97f88b1eb5472/Cartridges/bm_checkoutcom/cartridge/static/default/js/core/settings.js#L261

Related to issue: https://github.com/checkout/link_checkoutcom/issues/127

Please make sure all code comments are formatted according to standards.
// My comment

instead of

//My comment

**Comment by michael-ugborikoko-cko** [comment]
Comment changed to follow standards and pushed to git
