### ISSUE TITLE
Code formatting needed

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#136]
https://github.com/checkout/link_checkoutcom/blob/1f8842ade3d1c2c2ce7c8b2b234630960e986a15/Cartridges/bm_checkoutcom/cartridge/controllers/CKOSettings.js#L1

Related issue: https://github.com/checkout/link_checkoutcom/issues/127
All the code in this file needs code formatting according to js coding standards.

**Comment by michael-ugborikoko-cko** [comment]
done
