### ISSUE TITLE
Is response.println needed?

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#138]
https://github.com/checkout/link_checkoutcom/blob/1f8842ade3d1c2c2ce7c8b2b234630960e986a15/Cartridges/bm_checkoutcom/cartridge/controllers/CKOSettings.js#L72

Please remove response.println statements if not needed.

**Comment by michael-ugborikoko-cko** [comment]
Removed as not needed

**Comment by michael-ugborikoko-cko** [comment]
removed as not needed
