### ISSUE TITLE
Functions naming

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#139]
https://github.com/checkout/link_checkoutcom/blob/1f8842ade3d1c2c2ce7c8b2b234630960e986a15/Cartridges/bm_checkoutcom/cartridge/controllers/CKOSettings.js#L60

Please use explicit action prefixes in the functions names.
"get", "set", "list", "handle"...

Example:

getApms() instead of apms()

**Comment by michael-ugborikoko-cko** [comment]
name changed to setApmsSettings
