### ISSUE TITLE
Potential parse errors

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#140]
https://github.com/checkout/link_checkoutcom/blob/1f8842ade3d1c2c2ce7c8b2b234630960e986a15/Cartridges/bm_checkoutcom/cartridge/controllers/CKOSettings.js#L81

e is an object and cannot work with a println instruction supposed to output strings.
Please remove println statements if not necessary.

**Comment by michael-ugborikoko-cko** [comment]
Line removed as not necessary
