### ISSUE TITLE
Functions naming conventions

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#141]
https://github.com/checkout/link_checkoutcom/blob/1f8842ade3d1c2c2ce7c8b2b234630960e986a15/Cartridges/bm_checkoutcom/cartridge/controllers/CKOSettings.js#L223

Please follow camel case conventions in functions names. Update needed for all methods and functions not following this standard.

Ex: getCkoApmSettingsCustomObjects() instead of getCKOAPMSettingsCustomObjects()

**Comment by michael-ugborikoko-cko** [comment]
Function names changed to recommended naming convention.
