### ISSUE TITLE
Invalid methods comments format

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#149]
https://github.com/checkout/link_checkoutcom/blob/40741f0026a9df9dfe1c349033fd6ad448c1bd77/Cartridges/int_checkoutcom/cartridge/scripts/helpers/transactionHelper.js#L13

@michael-ugborikoko-cko , the methods comments format is invalid for all methods in this file.
 According to standards, methods comments should be formatted as following: 
    /**
     * My method comment.
     */

And not
// My method comment

This seems to be a regression in standards as these methods comments were initially implemented correctly. Please update all methods in this file, and also check all other methods comments in all files of the SG integration.

I can see for example that this regression on methods comment is also present in the transactionsHelper and eventHelper files.

**Comment by michael-ugborikoko-cko** [comment]
Done
