### ISSUE TITLE
Missing BIC field in SEPA Source

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#157]
https://github.com/checkout/link_checkoutcom/blob/c3abeed137c292fd7c763689e3c03f48f4532e13/Cartridges/int_checkoutcom/cartridge/scripts/config/ckoApmConfig.js#L235

@michael-ugborikoko-cko, is the BIC field missing in the SEPA payment source provide?

**Comment by michael-ugborikoko-cko** [comment]
not required for live or sandbox mode
