### ISSUE TITLE
Hard coded string

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#21]
https://github.com/checkout/link_checkoutcom/blob/8a21be9845a49b5d39bbe3f2431848596ab0f887/int_checkoutcom/cartridge/scripts/helpers/ckoUtility.js#L766

This string should not be hard coded. Please move it to an attribute-definition tag in system-object-definitions.xml, without assign it to an attribute-group so that it's not displayed on the UI. 

The string will still be retrievable using the ckoUtility.getValue() method.

**Comment by michael-ugborikoko-cko** [comment]
moved to custom preferences
