### ISSUE TITLE
APM custom preferences disappeared

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#26]
https://github.com/checkout/link_checkoutcom/blob/f274f607bce6ae9d88f0e97a279f2fc464d41ce0/metadata/meta/system-object-definitions.xml#L1

The APM custom preferences seem to have disappeared. Please add them back and:
1- Put all the APM parameters in a single separate group as it's currently done for Account Keys, Apple Pay, Google Pay and general settings. The APMs group should be named "Checkout.com APM".

2- Link the custom preferences parameters to each APM involved.

**Comment by michael-ugborikoko-cko** [comment]
Done
