### ISSUE TITLE
Incorrect naming of private shared key

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#28]
https://github.com/checkout/link_checkoutcom/blob/b5322df2ad09437854e0099fcc8f27ef8bdc4dc8/metadata/meta/system-object-definitions.xml#L235

Rename all occurrences, spaced and camel cased combinations of "Private Key" to "Private Shared Key" in the branch, according to the Hub wording.

**Comment by michael-ugborikoko-cko** [comment]
Done
