### ISSUE TITLE
Update language strings in .properties file

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#3]
https://github.com/checkout/link_checkoutcom/blob/f1b0b270633972586a75453c8631dfcab1d85a9e/int_checkoutcom/cartridge/templates/resources/cko.properties#L1

All language strings used in the code should be referenced in this .properties file.

**Comment by michael-ugborikoko-cko** [comment]
added local translation for sepa mandate form and apms
