### ISSUE TITLE
Hard coded sample data in ckoUtility

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#33]
https://github.com/checkout/link_checkoutcom/blob/5fd484dc57ecac97678d6a7339adc90bd77e38d6/int_checkoutcom/cartridge/scripts/helpers/ckoUtility.js#L1060

https://github.com/checkout/link_checkoutcom/blob/5fd484dc57ecac97678d6a7339adc90bd77e38d6/int_checkoutcom/cartridge/scripts/helpers/ckoUtility.js#L1085

Please avoid sample data in the code

**Comment by michael-ugborikoko-cko** [comment]
Done
