### ISSUE TITLE
Hardcoded currency values

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#34]
https://github.com/checkout/link_checkoutcom/blob/5fd484dc57ecac97678d6a7339adc90bd77e38d6/int_checkoutcom/cartridge/scripts/helpers/ckoUtility.js#L186

The currency codes for gateway request value calculation should be moved to a JSON file.

**Comment by michael-ugborikoko-cko** [comment]
Move to a config object. Done
