### ISSUE TITLE
0$ auth response always true for card payments

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#37]
https://github.com/checkout/link_checkoutcom/blob/eb6b12728e9ab80f3218ffb000ef486979a35e48/int_checkoutcom/cartridge/scripts/helpers/cardUtility.js#L31

The pre authorisation response for card payments always returns true. Please implement an effective test of the 0$ auth response returning true or false.

**Comment by michael-ugborikoko-cko** [comment]
uncomment the line above and removed test line 31. Done
