### ISSUE TITLE
Missing translation string in card payment form

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#42]
https://github.com/checkout/link_checkoutcom/blob/bfcdb73c5a5c97b9dd0a90a6c9621dab040371d4/int_checkoutcom/cartridge/forms/default/cardPaymentForm.xml#L8

The "PAY WITH CARD" string needs to follow the translation rules

**Comment by michael-ugborikoko-cko** [comment]
This line of code is not used in the form... its been commented out
