### ISSUE TITLE
JS code conventions

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#45]
https://github.com/checkout/link_checkoutcom/blob/bc73fc7914eda519cf9be6654ea7f89ca240b0a7/int_checkoutcom/cartridge/static/default/experience/alternativePayments.js#L1

Please make sure:
1- Every function starts with a lower case letter. Ex: myFunction() instead of MyFunction()
2- Every code comment starts with a capital letter. Ex: // My comment instead of // my comment
3- Every comment is relevant to the APM method processed. "multibanco" seems to be used as comment in many places for APMs that are not Multibanco.

**Comment by michael-ugborikoko-cko** [comment]
Done
