### ISSUE TITLE
JS code standards

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#46]
https://github.com/checkout/link_checkoutcom/blob/b585493bb0b9bda8c2afc47031ff17e30577c2bc/int_checkoutcom/cartridge/scripts/helpers/ckoUtility.js#L1

Please make sure every code comment starts with a capital letter in this file. Ex:
// My comment instead of // my comment.

**Comment by michael-ugborikoko-cko** [comment]
Done
