### ISSUE TITLE
Helper files consistency

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#5]
https://github.com/checkout/link_checkoutcom/blob/f1b0b270633972586a75453c8631dfcab1d85a9e/int_checkoutcom/cartridge/scripts/utility/util.js#L1

This utils.js file should be moved to the helpers folder and follow the existing naming conventions.
Suggested name: CKOUtilities.js
Suggested folder: /scripts/helpers

**Comment by michael-ugborikoko-cko** [comment]
Done
