### ISSUE TITLE
Exported/Public controller function name

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#56]
https://github.com/checkout/link_checkoutcom/blob/c7cd80cc603548f1e58481152100c3d5eddf0c9e/Cartridges/int_checkoutcom/cartridge/controllers/CKOKlarna.js#L65

Naming conventions should be strictly followed. The fist letter of exported/Public function names should be a capital letter. Please update the exported function name and all calls to the function in the code base.

**Comment by michael-ugborikoko-cko** [comment]
Done
