### ISSUE TITLE
Export http method

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#57]
https://github.com/checkout/link_checkoutcom/blob/b7b5d5fdcc86a8a9096b57ffea77ee8e526dfd79/Cartridges/int_checkoutcom/cartridge/controllers/CKOKlarna.js#L65

Please explicitly restrict the export method to an http method (POST or GET)

**Comment by michael-ugborikoko-cko** [comment]
Done
