### ISSUE TITLE
String missing translation

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#59]
https://github.com/checkout/link_checkoutcom/blob/b7b5d5fdcc86a8a9096b57ffea77ee8e526dfd79/Cartridges/int_checkoutcom/cartridge/controllers/CKOMain.js#L80

Please make the string translatable.

**Comment by michael-ugborikoko-cko** [comment]
Line removed and replaced with CKOHelper.handleFail(null);
