### ISSUE TITLE
Forbidden usage of reserved name for a function

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#6]
https://github.com/checkout/link_checkoutcom/blob/f1b0b270633972586a75453c8631dfcab1d85a9e/int_checkoutcom/cartridge/controllers/Klarna.js#L21

"session" is a reserved name that shouldn't be used for function naming. "session" is a global SFCC variable that could collide with other functions or variable using the same name, an. create unexpected behaviour.

**Comment by michael-ugborikoko-cko** [comment]
Done
