### ISSUE TITLE
String missing translation

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#60]
https://github.com/checkout/link_checkoutcom/blob/b7b5d5fdcc86a8a9096b57ffea77ee8e526dfd79/Cartridges/int_checkoutcom/cartridge/controllers/CKOSepa.js#L112

Please make the string translatable.
The first letter of the comment should also be a capital letter.

**Comment by michael-ugborikoko-cko** [comment]
Done
