### ISSUE TITLE
JS scripts at the end of the page

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#61]
https://github.com/checkout/link_checkoutcom/blob/b7b5d5fdcc86a8a9096b57ffea77ee8e526dfd79/Cartridges/int_checkoutcom/cartridge/templates/default/cardPayments/cardPaymentForm.isml#L73

Please move JS inclusions to the bottom of the file.

**Comment by michael-ugborikoko-cko** [comment]
Done...
