### ISSUE TITLE
Move inline CSS styles

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#67]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/alternativePayments.isml#L7

Please move all inline CSS styles to a separate CSS file.

**Comment by michael-ugborikoko-cko** [comment]
created apm.css and moved all css over

Done
