### ISSUE TITLE
Naming conventions for methods

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#68]
https://github.com/checkout/link_checkoutcom/blob/1c152dae3763d30dddcd7694f1bd022ddb81de93/Cartridges/int_checkoutcom/cartridge/scripts/helpers/apmHelper.js#L68

This method should be named "handleApmChargeResponse" and not "handleAPMChargeResponse". Please replace all references to this method according to camel case naming conventions.

**Comment by michael-ugborikoko-cko** [comment]
Done
