### ISSUE TITLE
Updated file and method naming

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#69]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L1

Rename this file to apm.js and rename the "toggleAPMS" method to "toggleApm".

**Comment by michael-ugborikoko-cko** [comment]
File renamed to apm.js
and function changed to toggleApm

Done
