### ISSUE TITLE
Billing descriptor fields required in Site Preferences

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#7]
The billing descriptor fields should not be mandatory in the site preferences. It's currently impossible to save the configuration form without providing values.

After making these fields optional, the part of the payment request handling billing descriptors should also make sure the fields are not empty before being added to a payment request

**Comment by michael-ugborikoko-cko** [comment]
Done

**Comment by michael-ugborikoko-cko** [comment]
Done

**Comment by david-fiaty-cko** [comment]
It seems that this issue appeared again after reverting changes on the branch. Please update the branch.

**Comment by michael-ugborikoko-cko** [comment]
Done - mandatory property changed to false for billingDescriptor1 and 2.
