### ISSUE TITLE
File and folder renaming

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#70]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/alternativePayments.isml#L1

Rename this file to "apm.js" and its parent folder to "apm".

**Comment by michael-ugborikoko-cko** [comment]
file renamed to apm and folder to apm

Done
