### ISSUE TITLE
Rename a variable

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#71]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L24

"apm" already contains the word "payment", which makes "apm_payment_types" a repetition of the word "payment". Please rename all occurrences of this variable to "apm_list".

**Comment by michael-ugborikoko-cko** [comment]
changed to apm_type

Done

**Comment by michael-ugborikoko-cko** [comment]
changed to apm_list
