### ISSUE TITLE
Rename a file

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#72]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/redirects/APM.isml#L1

Rename this file to "apm.isml" instead of "APM.isml"

**Comment by michael-ugborikoko-cko** [comment]
file name changed to apm

Done
