### ISSUE TITLE
BenefitPay APM file naming

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#74]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/benefit.isml#L1

Please rename this template file using the actual name of the APM: "benefitPay.isml".

**Comment by michael-ugborikoko-cko** [comment]
filename changed to benefitPay

Done
