### ISSUE TITLE
Przelewy24 APM file naming

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#76]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/p24.isml#L1

Please rename this template file using the actual name of the APM: "przelewy24.isml".

**Comment by michael-ugborikoko-cko** [comment]
Done
