### ISSUE TITLE
Bancontact missing translation string

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#77]
https://github.com/checkout/link_checkoutcom/blob/e8f6c4bbcd986e36996dae4df0b546fb08495348/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/bancontact.isml#L3

Please translate the "Edit" string and use the name of. the APM the alt attribute.
Example: 	
alt="${Resource.msg('cko.bancontact.name','cko',null)}"
value="${Resource.msg('cko.button.edit','cko',null)}" 

This has to be done for all APMs in all templates.

**Comment by michael-ugborikoko-cko** [comment]
alt's added
and Edit removed. not needed
Done
