### ISSUE TITLE
HTML tag formatting

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#79]
https://github.com/checkout/link_checkoutcom/blob/1c152dae3763d30dddcd7694f1bd022ddb81de93/Cartridges/int_checkoutcom/cartridge/templates/default/alternativePayments/eps.isml#L2

HTML tags should be lowercase. "h4" and not. "H4". See HTML standards.
Please double check all APM templates files as fawry.isml for example has the same issue.

**Comment by michael-ugborikoko-cko** [comment]
Done
