### ISSUE TITLE
Remove APM load click event

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#85]
https://github.com/checkout/link_checkoutcom/blob/aa10e72482f8e278da4d9de9bbeeebda52c6835d/Cartridges/int_checkoutcom/cartridge/static/default/js/apm.js#L403

The APMs tab content should be loaded on page load. Please remove the tab click event.

**Comment by michael-ugborikoko-cko** [comment]
Done
