### ISSUE TITLE
Remove spaces before language strings

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#87]
https://github.com/checkout/link_checkoutcom/blob/aa10e72482f8e278da4d9de9bbeeebda52c6835d/Cartridges/int_checkoutcom/cartridge/templates/resources/cko.properties#L27

Please make sure there is no space before language strings. Example:
Good: cko.bancontact.name=Bancontact
Bad: cko.bancontact.name= Bancontact

Please check all strings in all languages files as the issue shows in many places.

**Comment by michael-ugborikoko-cko** [comment]
done
