### ISSUE TITLE
HTML 5 standards

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#88]
https://github.com/checkout/link_checkoutcom/blob/aa10e72482f8e278da4d9de9bbeeebda52c6835d/Cartridges/int_checkoutcom/cartridge/templates/default/apm/eps.isml#L9

Please replace all occurrences of "<hr/>" by "<hr>" to respect the HTML 5 coding standards.
Same for all "<input/>". The should be replaced by "<input>".

**Comment by michael-ugborikoko-cko** [comment]
Done
