### ISSUE TITLE
Images width in APM templates

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#89]
https://github.com/checkout/link_checkoutcom/blob/aa10e72482f8e278da4d9de9bbeeebda52c6835d/Cartridges/int_checkoutcom/cartridge/templates/default/apm/eps.isml#L3

Please move the width="10%" attribute to the apm.css file and apply the with with a single selector as following:

#apmsBox h4 img {
  width: 10%;
}

**Comment by michael-ugborikoko-cko** [comment]
Done
