### ISSUE TITLE
Remove type attribute from image tags

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#90]
https://github.com/checkout/link_checkoutcom/blob/aa10e72482f8e278da4d9de9bbeeebda52c6835d/Cartridges/int_checkoutcom/cartridge/templates/default/apm/eps.isml#L3

An image tag doesn't need a type="image" attribute.
Please check and remove the type="image" attribute from all image tags.

**Comment by michael-ugborikoko-cko** [comment]
Done
