### ISSUE TITLE
Update comments in language file

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#91]
https://github.com/checkout/link_checkoutcom/blob/38a7f218b48e4177012bf578a2a23eb2fd35ba5b/Cartridges/int_checkoutcom/cartridge/templates/resources/forms_en.properties#L2

Please remove your name from the code comments.
No comments actually needed in this file.

**Comment by michael-ugborikoko-cko** [comment]
DONE
