### ISSUE TITLE
Variable naming conventions

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#95]
https://github.com/checkout/link_checkoutcom/blob/8c66abc90e97f68976a66f1465bbf5ecdee17045/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L569

The "Address" variable should be "address" without a capital A according to JS naming conventions.

**Comment by michael-ugborikoko-cko** [comment]
Done
