### ISSUE TITLE
Use of reserved variable name

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#96]
https://github.com/checkout/link_checkoutcom/blob/8c66abc90e97f68976a66f1465bbf5ecdee17045/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L569

"Object" is a reserved name in Javascript and should not be used to name a variable.
Please rename "Object" to "requestData".

**Comment by michael-ugborikoko-cko** [comment]
Done
