### ISSUE TITLE
Code improvement needed

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#97]
https://github.com/checkout/link_checkoutcom/blob/8c66abc90e97f68976a66f1465bbf5ecdee17045/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L558

Please fix the following:

1- Variable names should start with a lowercase letter
2- CSS styles should be moved to a separate CSS file. and not coded inline in a javascript file.

**Comment by michael-ugborikoko-cko** [comment]
Done
