### ISSUE TITLE
Missing space after case directive in switch statement

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#98]
https://github.com/checkout/link_checkoutcom/blob/8c66abc90e97f68976a66f1465bbf5ecdee17045/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L26

Please add a space after each "case" directive in the switch statement. See coding standards.

**Comment by michael-ugborikoko-cko** [comment]
done
