### ISSUE TITLE
Missing string translation

### ISSUE THREAD

**Issue by david-fiaty-cko** [checkout/link_checkoutcom#99]
https://github.com/checkout/link_checkoutcom/blob/8c66abc90e97f68976a66f1465bbf5ecdee17045/Cartridges/int_checkoutcom/cartridge/static/default/js/alternativePayments.js#L78

Please translate the string or remove the "default" directive (recommended).

**Comment by michael-ugborikoko-cko** [comment]
I don't know how to include a translation string for a static js file

**Comment by michael-ugborikoko-cko** [comment]
line removed from code
